### ISSUE TITLE
Run queries in background

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#232]

**Comment by thomaslevesque** [comment]
I can't reply in the marketplace comments, so I reproduce the conversation here

> Me: Nice tool, but queries *really* need to be executed in the background. Executing a long running query freezes Visual Studio.

> ErikEJ: Thanks for the suggestion - first time I got that feedback, actually, wonder why your query is so slow? - I have logged https://github.com/ErikEJ/SqlCeToolbox/issues/232

In this case, it was slow because it was badly optimized; I was trying to improve it and accidentally made it much slower. So it's something that can happen pretty easily, e.g. you just forget a WHERE clause, and you have to kill VS to stop it... There are also cases where a query can legitimately take a long time, e.g. when there's a large volume of data (admittedly SQLite or SQL CE databases are usually not that big)

**Comment by ErikEJ** [comment]
Thanks, I will investigate the options for implementing this

**Comment by ErikEJ** [comment]
Any samples for making synchronous code run in background (other than Backgroundworker?)

**Comment by thomaslevesque** [comment]
> Any samples for making synchronous code run in background (other than Backgroundworker?)

I would just use [`ExecuteReaderAsync`](https://msdn.microsoft.com/en-us/library/hh223679(v=vs.110).aspx), if the underlying provider implements it (the base implementation just runs synchronously and returns a completed task), or `Task.Run` if it doesn't. Support for cancellation would be great too!

**Comment by ErikEJ** [comment]
OK, none of the providers support Async, so I will experiment with Task.Run - thanks!

**Comment by ErikEJ** [comment]
This has been fixed in the latest daily build, download links here: https://github.com/ErikEJ/SqlCeToolbox - please let me know if it works for you - and thanks for your feedback!

**Comment by thomaslevesque** [comment]
Wow, that was fast! Thanks, I'll give it a try ASAP.

**Comment by thomaslevesque** [comment]
@ErikEJ, it seems to work fine, but when I execute the query, there's nothing to indicate that it is running, or preventing me from executing it again. If the query takes more than 1 or 2 seconds, users will think they didn't actually click "execute" and will try to do it again... There should probably be a visual indicator, and the execute button should be disabled.

**Comment by ErikEJ** [comment]
OMG - how long does you sqlite query run for? I get 100.000 rows back in subseconds??
I have fixed this (disabled buttons) in latest daily build...

**Comment by ErikEJ** [comment]
I this fixes your issue with the Toolbox, I would be very grateful if you could update your review on the MarketPlace 😄

**Comment by thomaslevesque** [comment]
> OMG - how long does you sqlite query run for? I get 100.000 rows back in subseconds??

Well, the particular query I was having a problem with took 20 minutes to run... after fixing it, it took 300 milliseconds ;). It's not fetching the data that was taking a long time (there was about 12k rows to fetch out of 120k), but just executing the query (a recursive CTE on a SQLite db); adding a criteria caused SQLite to use an index that was making things worse instead of better...

I know it's unusual to have query that take that long, but it can happen (possibly by accident), so the tool has to handle this case.

> I have fixed this (disabled buttons) in latest daily build...

👍
Adding a ProgressBar in indeterminate state would probably help the user understand that a query is running.

I'll try the new build.

**Comment by thomaslevesque** [comment]
It works, but as I said, it still doesn't look like it's doing anything; the only indication is the disabled button.

**Comment by ErikEJ** [comment]
Added progress bar in latest build

**Comment by thomaslevesque** [comment]
> Added progress bar in latest build

Looking good 👍 
Thanks for the quick fixes!

**Comment by thomaslevesque** [comment]
Now, what would be even better is to be able to abort the query. But unfortunately it's probably not going to be easy, according to this: http://stackoverflow.com/questions/2781484/abort-call-to-unmanaged-dll

Basically, it would require running the query in a separate process...

**Comment by ErikEJ** [comment]
You are welcome - I have no plans to support cancellation at the moment.
I would be very grateful if you would update your VS Market Place review/rating!

**Comment by thomaslevesque** [comment]
I just did. Thanks again!
