### ISSUE TITLE
DateTime Format dropdown not working correctly when it creates the connection string

### ISSUE THREAD

**Issue by ImGonaRot** [ErikEJ/SqlCeToolbox#779]
I am using version 4.7.632.0 for SSMS 

My sqlite DB is using "ticks" for "datetime" fields in the database.
When I add a connection using the SQLite toolbox and select "Ticks" from the DateTime Format dropdown it creates a connection like the following:

> data source=test.db;DateTime Format=Ticks

BUT if you query any of the tables with DateTime fields you will receive "String was not recognized as a valid DateTime."

IF I manually use the "ConnectionString" text box in the add connection and use the following connection string:
> data source=test.db;datetimeformat=Ticks

This works without errors.
Notice that there is a "space" in the "broken" version.

I think the connection string builder for the "Add SQLite Connection" controls needs to remove the space when building the connection string.

**Comment by ErikEJ** [comment]
Strange - I am using the Connection string builder from System.Data.SQLite

**Comment by ImGonaRot** [comment]
The connection string builder does work fine but it is not adding the correct "datetimeformat".
I can upload test sqlite db for you if you would like to reproduce?

**Comment by ErikEJ** [comment]
Yes, I get that, but the connection string builder is beyond my control: http://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki

**Comment by ImGonaRot** [comment]
When I select the following in the "Add SQLite Connection" box it creates the following:
![image](https://user-images.githubusercontent.com/8114712/53750884-f772bc00-3e78-11e9-8bbe-2056a5644ea8.png)

Notice the "space" when I hover the database in SSMS.
![image](https://user-images.githubusercontent.com/8114712/53751327-0a39c080-3e7a-11e9-864c-e6e1082b2d1b.png)

Now if I do the following in "Add SQLite Connection" box is creates the following:
![image](https://user-images.githubusercontent.com/8114712/53752689-41f63780-3e7d-11e9-8fbc-684fa6fcff81.png)

Note there is "no space" when I hover the database in SSMS.
![image](https://user-images.githubusercontent.com/8114712/53751182-b5964580-3e79-11e9-9e20-7db2a0edf5bf.png)

**Comment by ErikEJ** [comment]
Yes, I understand the issue. But how the connection string is formatted using the builder is not something I can control, sorry. Seems like a bug in system.data.sqlite

**Comment by ImGonaRot** [comment]
Oh sorry I thought your tool was the once creating the connection string based on the selection in the toolbox. Do you know who created this connection string builder toolbox so I can post the question there?

**Comment by ErikEJ** [comment]
Try here: http://system.data.sqlite.org/index.html/ticket

**Comment by ErikEJ** [comment]
Closing as this is an external issue

**Comment by ImGonaRot** [comment]
@ErikEJ I submitted the bug to the SQLite ticket site you suggested and they posted that it might be the caller is using the "DisplayName" property which does include a space for display purpose. Not sure if that helps any. Here is the link to the ticket.
https://system.data.sqlite.org/index.html/tktview/ee2c42b4678488f85030265105bf96db13721ff1

**Comment by ErikEJ** [comment]
Obviously the SqliteConnectionStringBuilder is buggy and cannot be relied on - I will change the SQLite connection dialog to be more simple (like the SQL Compact one)

**Comment by ErikEJ** [comment]
@ImGonaRot Fixed in latest daily build, please let me know if that resolves your issue

**Comment by ImGonaRot** [comment]
Thanks for looking into the problem. 
I did download the latest source code and built the SSMSToolbox project which created a SSMSToolbox.vsix but that produces and error anytime I try to install.
![image](https://user-images.githubusercontent.com/8114712/68091156-36af3d80-fe4a-11e9-89fa-7748c6c1764c.png)

11/3/2019 2:55:32 PM - Searching for applicable products...
11/3/2019 2:55:32 PM - Found installed product - Microsoft Visual Studio Professional 2015
11/3/2019 2:55:32 PM - Found installed product - Microsoft Visual Studio Community 2015
11/3/2019 2:55:32 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
11/3/2019 2:55:32 PM - Found installed product - Global Location
11/3/2019 2:55:32 PM - Found installed product - Visual Studio Professional 2019
11/3/2019 2:55:32 PM - Found installed product - Visual Studio Professional 2017
11/3/2019 2:55:32 PM - Capping recursion at 5 directories in each extension root due to 'default limit'.

I do have SSMS 18 installed but the vsix installer does not see the SSMS 18 installed.

I also built the VSToolbox project which created a SqlCeVsToolbox.vsix and that installed fine into VS2019 as version 4.7.210.0 when I select the about box in the control and lists it as 4.7.644 in the VS 2019 Extension manager.
![image](https://user-images.githubusercontent.com/8114712/68091424-76c3ef80-fe4d-11e9-822a-f9a12b124cd6.png)

BUT it still threw the error "String was not recognized as a valid DateTime"
AND it still has a space between "DateTime Format" in the connection string.

I'm not sure how to install the updated version of the SSMSToolbox?

**Comment by ErikEJ** [comment]
Why build the code?? Just get the latest daily build, and follow the install instructions here. https://github.com/ErikEJ/SqlCeToolbox#sql-server-management-studio-ssms-18x-extension 

notice: **If you have trouble installing the SSMS extension, try the following command line:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe" "full path to extension.vsix"**

**Comment by ImGonaRot** [comment]
Sorry I should have mentioned earlier that I went down that path.
The page has an area for "SQL Server Management Studio (SSMS) 18.x Extension"
both for the "Release" -- Visual Studio MarketPlace
and for "Daily build"

The "Release" link will take you to an older version of the SSMSToolbox.vsix
The "Daily build" link will download the "extension.vsix"  http://vsixgallery.com/extensions/d6c77c32-fe4b-4f6d-ad5d-f7b755212760/extension.vsix
Which gives the same error as the built version I tried of SSMSToolbox.vsix where it does not see any versions of SSMS installed. (I have both SSMS 17 & SSMS 18 installed)
I also tried the command line vsixinstaller from both VS 2017 and VS 2019 but no luck.
I have also tried to uninstall / re-install both SSMS 17 & SSMS 18. No luck.
Still digging.

But with all that said, is it fixed in VS 2019 extension? Do I have the correct version 4.7.644?

**Comment by ImGonaRot** [comment]
Still can't get it to install in SSMS 17 or 18, but here is what I have tried so far...

I have the latest version of SSMSToolbox (4.7.210 4.8-alpha1) from github.
I put it in debug mode and it does launch SSMS 17
When debugging, it creates the following folder
"C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Extensions\SqlCeToolbox"
With SSMSToolbox.dll version 4.7.210 4.8-alpha1 in the SqlCeToolbox Extensions folder.
When VS 2019 debugger launches SSMS 17, and I go help / about for the SQLite / SQL Server Compact Toolbox for SSMS, it is version 4.7.632.0 in that about box.
![image](https://user-images.githubusercontent.com/8114712/68092248-39645f80-fe57-11e9-8c4b-caac03ab5647.png)


Inside SSMS 17, if I add an existing database and select DateTime Format = Ticks, it still adds it wrong with a connection string containing a space between "DateTime Format" when I hover the database.
BUT this time it does not crash with the "String was not recognized as a valid DateTime"...
INSTEAD it does open the table and the DateTime column looks like ticks rather than DateTime.

If I remove the space between "DateTime Format" on the connection string, it shows the DateTime column correctly.

![image](https://user-images.githubusercontent.com/8114712/68092215-d8d52280-fe56-11e9-8b05-75023d9d7767.png)

**Comment by ErikEJ** [comment]
It should not launch SSMS 17, but 18 ! It still does not sound like you are using the latest daily build!

**Comment by ErikEJ** [comment]
It should also be fixed in the latest daily of the VS Toolbox, yes

**Comment by ErikEJ** [comment]
I will try out the installer issues and come back to you.

**Comment by ErikEJ** [comment]
The daily build version is 4.7.659 or later for all types of extensions, btw

**Comment by ErikEJ** [comment]
I have published installation instructions here: https://github.com/ErikEJ/SqlCeToolbox/blob/master/README.md#installing-the-ssms-18-extension

**Comment by ImGonaRot** [comment]
Thank for the updated VSIX and the instructions for SSMS 18.
I was able to follow the instructions and extracted to SSMS 18 and it launches.

The new version does indeed remove the space between the "DateTime Format"
`data source=test.db;DateTimeFormat=Ticks`

Thanks for such a great tool.
